In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('/Users/goranmuricuser/Downloads/citations.csv').sort_values(by='Year', ascending=False).fillna('')

In [3]:
df

,Authors,Title,Publication,Volume,Number,Pages,Year,Publisher
45,"Bibal, Adrien; Gerlek, Nathaniel; Muric, Goran...",Automating Annotation Guideline Improvements u...,Proceedings of Context and Meaning: Navigating...,,,129-144,2025.0,
40,"Schmitz, Matheus; Muric, Goran; Hickey, Daniel...",Do users adopt extremist beliefs from exposure...,Social Network Analysis and Mining,14.0,1,1-12,2024.0,Springer Vienna
44,"Zimmerman, Federico; Bailey, David D; Muric, G...",Attraction to politically extreme users on soc...,PNAS nexus,3.0,10,pgae395,2024.0,Oxford University Press US
43,"Hickey, Daniel; Schmitz, Matheus; Fessler, Dan...",Hostile Counterspeech Drives Users From Hate S...,arXiv preprint arXiv:2405.18374,,,,2024.0,
42,"Muric, Goran; Delay, Ben; Minton, Steven;",Interpretable Cross-Examination Technique (ICE...,arXiv preprint arXiv:2303.13641,,,,2024.0,
39,"Twyman, Marlon; Murić, Goran; Zheng, Weiwei;",Positioning in a collaboration network and per...,Journal of Computer-Mediated Communication,28.0,4,zmad024,2023.0,Oxford University Press
36,"Schmitz, Matheus; Murić, Goran; Burghardt, Kei...",Quantifying How Hateful Communities Radicalize...,IEEE/ACM International Conference on Advances ...,,,,2023.0,
35,"Schmitz, Matheus; Muric, Goran; Burghardt, Kei...",Detecting anti-vaccine users on Twitter,Proceedings of the International AAAI Conferen...,17.0,,787-795,2023.0,
38,"Hickey, Daniel; Schmitz, Matheus; Fessler, Dan...",Auditing Elon Musk’s impact on hate speech and...,Proceedings of the international AAAI conferen...,17.0,,1133-1137,2023.0,
37,"Hickey, Daniel; Schmitz, Matheus; Fessler, Dan...",No love among haters: Negative interactions re...,arXiv preprint arXiv:2303.13641,,,,2023.0,
31,"Chen, Emily; Jiang, Julie; Chang, Ho-Chun Herb...",Charting the information and misinformation la...,Jmir Infodemiology,2.0,1,e32378,2022.0,"JMIR Publications Toronto, Canada"
32,"Zhang, Weiwei; Muric, Goran; Ferrara, Emilio;",Individual and collective performance deterior...,arXiv preprint arXiv:2205.09693,,,,2022.0,
33,"Murić, Goran; Tregubov, Alexey; Blythe, Jim; A...",Large-scale agent-based simulations of online ...,Autonomous Agents and Multi-Agent Systems,36.0,2,38,2022.0,Springer US New York
34,"Jiang, Julie; Chen, Emily; Luceri, Luca; Murić...",What are your pronouns? Examining gender prono...,arXiv preprint arXiv:2207.10894,,,,2022.0,
22,"Heimann, Mark; Murić, Goran; Ferrara, Emilio;",Structural Node Embedding in Signed Social Net...,Complex Networks & Their Applications IX,,,3-14,2021.0,"Springer, Cham"
30,"Ko, Kaitlyn; Burghardt, Keith; Muric, Goran;",Enter at your own risk: The impacts of joining...,2021 IEEE 18th International Conference on Mob...,,,657-658,2021.0,IEEE
29,"Muric, Goran; Wu, Yusong; Ferrara, Emilio;",COVID-19 Vaccine Hesitancy on Social Media: Bu...,JMIR Public Health Surveill,7.0,11,,2021.0,JMIR Public Health and Surveillance
28,"Ho-Chun Herbert Chang, Emily Chen, Meiqing Zha...",Social Bots and Social Media Manipulation in 2...,"Handbook of Computational Social Science, Volu...",,,185,2021.0,Routledge
26,"Schmitz, Matheus; Murić, G; Burghardt, Keith;",A Python Package to Detect Anti-Vaccine Users ...,,,,,2021.0,
24,"Nghiem, Huy; Muric, Goran; Morstatter, Fred; F...",Detecting cryptocurrency pump-and-dump frauds ...,Expert Systems with Applications,182.0,,115284,2021.0,Pergamon
23,"Muric, Goran; Lerman, Kristina; Ferrara, Emilio;",Gender Disparity in the Authorship of Biomedic...,Journal of Medical Internet Research,23.0,4,e25379,2021.0,"JMIR Publications Inc., Toronto, Canada"
41,"Chang, HCH; Chen, E; Zhang, M; Muric, G; Ferra...",Handbook of computational social science,London: Routledge,,,,2021.0,
21,"Ferrara, Emilio; Chang, Herbert; Chen, Emily; ...",Characterizing social media manipulation in th...,First Monday,25.0,11,,2020.0,
20,"Ross, Clara O; Gupta, Aditya; Mehrabi, Ninareh...",The leaky pipeline in physics publishing,arXiv preprint arXiv:2010.08912,,,,2020.0,
18,"Murić, Goran; Tregubov, Alexey; Blythe, Jim; A...",Massive Cross-Platform Simulations of Online S...,Proceedings of the 19th International Conferen...,,,,2020.0,
16,"Ozer, Mert; Sapienza, Anna; Abeliuk, Andrés; M...",Discovering patterns of online popularity from...,Expert Systems with Applications,151.0,,113337,2020.0,Pergamon
15,"Blythe, Jim; Bollenbacher, John; Huang, Di; Hu...",Massive multi-agent data-driven simulations of...,Advances in Practical Applications of Survivab...,,,3-15,2019.0,Springer International Publishing
14,"Murić, Goran; Abeliuk, Andres; Lerman, Kristin...",Collaboration drives individual productivity,Proceedings of the ACM on Human-Computer Inter...,3.0,CSCW,1-24,2019.0,"ACM New York, NY, USA"
17,"Blythe, James; Ferrara, Emilio; Huang, Di; Ler...",The DARPA SocialSim Challenge: Massive Multi-A...,AAMAS,,,1835-1837,2019.0,
13,"Muric, Goran;",Resilience of the Critical Communication Netwo...,,,,,2017.0,
8,"Murić, Goran; Jorswieck, Eduard; Scheunert, Ch...",Using LTI dynamics to identify the influential...,Plos one,11.0,12,e0168514,2016.0,"Public Library of Science San Francisco, CA USA"
7,"Murić, Goran; Scheunert, Christian; Jorswieck,...",On modeling epidemics in networks using linear...,2015 IEEE 11th International Conference on Wir...,,,138-146,2015.0,IEEE
25,"RADA, POLOŽAJA ŽENA NA TRŽIŠTU;",ISTRAŽIVANJE O ULOZI ZNANJA IZ OBLASTI IKT I,,,,,2014.0,
9,"Murić, Goran; Bogojević, Dragan; Gospić, Nataša;",Interdependencies of communication and electri...,ICIST 2014 - 4th International Conference on I...,,,,2014.0,Society for Information Systems and Computer N...
46,"Muric, Goran; Macura, Dragana; Gospic, Natasa;...",An approach to assess criticality of elements ...,2013 11th International Conference on Telecomm...,,,,2013.0,
12,"Murić, Goran; Macura, Dragana; Gospić, Nataša;...",An Approach to Critical Information Infrastruc...,Business Information Security Conference BISEC...,,,,2013.0,
11,"Samcovic, Andreja; Muric, Goran;",Application of Digital Watermarking Technique ...,Business Information Security Conference BISEC...,,,,2013.0,
10,"Murić, Goran; Gospić, Nataša; Šelmić, Milica;",Protecting Critical Information Infrastructure...,International conference on Applied Internet a...,,,,2013.0,
5,"Murić, Goran; Gospić, Nataša; Bogojević, Dragan;",Proposal for possible approach for Critical In...,3rd International Conference on Information So...,,,,2013.0,
4,"Gospić, Nataša; Murić, Goran; Bogojević, Dragan;",The Method for Importance of Elements Assessme...,The Symposium on Novel Technologies in Postal ...,,,,2013.0,
3,"Murić, Goran; Macura, Dragana; Gospić, Nataša;...",An approach to assess criticality of elements ...,"Telecommunication in Modern Satellite, Cable a...",1.0,,141-144,2013.0,IEEE
1,"Gospić, Nataša; Murić, Goran; Bogojević, Dragan;",Managing critical infrastructure for sustainab...,E-society Journal,51.0,,,2012.0,
19,"Murić, Goran; Krsmanović, Maja;",ORSA - Organizing Software Application,AIIT - International Conference on Applied Int...,,,,2012.0,
6,"Bogojevic, Dragan; Gospic, Natasa; Muric, Goran;",Broadband universal service and access: trends...,2012 20th Telecommunications Forum (TELFOR),,,60-63,2012.0,IEEE
0,"Gospić, Nataša; Murić, Goran; Bogojević, Dragan;",Defining of Critical Telecommunication Infrast...,The Symposium on Novel Technologies in Postal ...,,,,2012.0,
2,"Krsmanović, Maja; Murić, Goran; Gospić, Nataša;",Improvement of children safety by using RFID b...,19thTelecommunications Forum (TELFOR) Proceedi...,,,130-133,2011.0,IEEE
27,"Ozer, Mert; Sapienza, Anna; Abeliuk, Andrés; M...",Discovering patterns of online popularity from...,,,,,,

In [ ]:
i = 1
for index, row in df.iterrows():
    if 'Supplementary' not in row['Title']:
        authors = row['Authors'].split(';')
        authors = [a.strip() for a in authors if a!=' ']
        auths = ''
        for a in authors:
            a1 = a.split(',')[0]
            a2 = a.split(',')[1]
            auths = auths + a1 + ' ' + a2[1] + ', '
        auths = auths[:-2]

        gscholar_link = 'https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q='

        title = row['Title']
        s = (gscholar_link+auths.replace(', ','%2C')+ '+' + title).replace(' ','+')
        year = str(int(row['Year'])) if row['Year'] != '' else ''
        #print(auths + ' (' + year + '). ' + title + '. ' + row['Publication'] + ' ' + year + ';')
        print(str(i) + '. ' + auths + ' ' + '[' + title + '.](' + s + ')' + ' ' + row['Publication'] + ' ' + year + ';' + str(row['Volume']))


        i+=1

In [6]:
df

,Authors,Title,Publication,Volume,Number,Pages,Year,Publisher
45,"Bibal, Adrien; Gerlek, Nathaniel; Muric, Goran...",Automating Annotation Guideline Improvements u...,Proceedings of Context and Meaning: Navigating...,,,129-144,2025.0,
40,"Schmitz, Matheus; Muric, Goran; Hickey, Daniel...",Do users adopt extremist beliefs from exposure...,Social Network Analysis and Mining,14.0,1,1-12,2024.0,Springer Vienna
44,"Zimmerman, Federico; Bailey, David D; Muric, G...",Attraction to politically extreme users on soc...,PNAS nexus,3.0,10,pgae395,2024.0,Oxford University Press US
43,"Hickey, Daniel; Schmitz, Matheus; Fessler, Dan...",Hostile Counterspeech Drives Users From Hate S...,arXiv preprint arXiv:2405.18374,,,,2024.0,
42,"Muric, Goran; Delay, Ben; Minton, Steven;",Interpretable Cross-Examination Technique (ICE...,arXiv preprint arXiv:2303.13641,,,,2024.0,
39,"Twyman, Marlon; Murić, Goran; Zheng, Weiwei;",Positioning in a collaboration network and per...,Journal of Computer-Mediated Communication,28.0,4,zmad024,2023.0,Oxford University Press
36,"Schmitz, Matheus; Murić, Goran; Burghardt, Kei...",Quantifying How Hateful Communities Radicalize...,IEEE/ACM International Conference on Advances ...,,,,2023.0,
35,"Schmitz, Matheus; Muric, Goran; Burghardt, Kei...",Detecting anti-vaccine users on Twitter,Proceedings of the International AAAI Conferen...,17.0,,787-795,2023.0,
38,"Hickey, Daniel; Schmitz, Matheus; Fessler, Dan...",Auditing Elon Musk’s impact on hate speech and...,Proceedings of the international AAAI conferen...,17.0,,1133-1137,2023.0,
37,"Hickey, Daniel; Schmitz, Matheus; Fessler, Dan...",No love among haters: Negative interactions re...,arXiv preprint arXiv:2303.13641,,,,2023.0,
31,"Chen, Emily; Jiang, Julie; Chang, Ho-Chun Herb...",Charting the information and misinformation la...,Jmir Infodemiology,2.0,1,e32378,2022.0,"JMIR Publications Toronto, Canada"
32,"Zhang, Weiwei; Muric, Goran; Ferrara, Emilio;",Individual and collective performance deterior...,arXiv preprint arXiv:2205.09693,,,,2022.0,
33,"Murić, Goran; Tregubov, Alexey; Blythe, Jim; A...",Large-scale agent-based simulations of online ...,Autonomous Agents and Multi-Agent Systems,36.0,2,38,2022.0,Springer US New York
34,"Jiang, Julie; Chen, Emily; Luceri, Luca; Murić...",What are your pronouns? Examining gender prono...,arXiv preprint arXiv:2207.10894,,,,2022.0,
22,"Heimann, Mark; Murić, Goran; Ferrara, Emilio;",Structural Node Embedding in Signed Social Net...,Complex Networks & Their Applications IX,,,3-14,2021.0,"Springer, Cham"
30,"Ko, Kaitlyn; Burghardt, Keith; Muric, Goran;",Enter at your own risk: The impacts of joining...,2021 IEEE 18th International Conference on Mob...,,,657-658,2021.0,IEEE
29,"Muric, Goran; Wu, Yusong; Ferrara, Emilio;",COVID-19 Vaccine Hesitancy on Social Media: Bu...,JMIR Public Health Surveill,7.0,11,,2021.0,JMIR Public Health and Surveillance
28,"Ho-Chun Herbert Chang, Emily Chen, Meiqing Zha...",Social Bots and Social Media Manipulation in 2...,"Handbook of Computational Social Science, Volu...",,,185,2021.0,Routledge
26,"Schmitz, Matheus; Murić, G; Burghardt, Keith;",A Python Package to Detect Anti-Vaccine Users ...,,,,,2021.0,
24,"Nghiem, Huy; Muric, Goran; Morstatter, Fred; F...",Detecting cryptocurrency pump-and-dump frauds ...,Expert Systems with Applications,182.0,,115284,2021.0,Pergamon
23,"Muric, Goran; Lerman, Kristina; Ferrara, Emilio;",Gender Disparity in the Authorship of Biomedic...,Journal of Medical Internet Research,23.0,4,e25379,2021.0,"JMIR Publications Inc., Toronto, Canada"
41,"Chang, HCH; Chen, E; Zhang, M; Muric, G; Ferra...",Handbook of computational social science,London: Routledge,,,,2021.0,
21,"Ferrara, Emilio; Chang, Herbert; Chen, Emily; ...",Characterizing social media manipulation in th...,First Monday,25.0,11,,2020.0,
20,"Ross, Clara O; Gupta, Aditya; Mehrabi, Ninareh...",The leaky pipeline in physics publishing,arXiv preprint arXiv:2010.08912,,,,2020.0,
18,"Murić, Goran; Tregubov, Alexey; Blythe, Jim; A...",Massive Cross-Platform Simulations of Online S...,Proceedings of the 19th International Conferen...,,,,2020.0,
16,"Ozer, Mert; Sapienza, Anna; Abeliuk, Andrés; M...",Discovering patterns of online popularity from...,Expert Systems with Applications,151.0,,113337,2020.0,Pergamon
15,"Blythe, Jim; Bollenbacher, John; Huang, Di; Hu...",Massive multi-agent data-driven simulations of...,Advances in Practical Applications of Survivab...,,,3-15,2019.0,Springer International Publishing
14,"Murić, Goran; Abeliuk, Andres; Lerman, Kristin...",Collaboration drives individual productivity,Proceedings of the ACM on Human-Computer Inter...,3.0,CSCW,1-24,2019.0,"ACM New York, NY, USA"
17,"Blythe, James; Ferrara, Emilio; Huang, Di; Ler...",The DARPA SocialSim Challenge: Massive Multi-A...,AAMAS,,,1835-1837,2019.0,
13,"Muric, Goran;",Resilience of the Critical Communication Netwo...,,,,,2017.0,
8,"Murić, Goran; Jorswieck, Eduard; Scheunert, Ch...",Using LTI dynamics to identify the influential...,Plos one,11.0,12,e0168514,2016.0,"Public Library of Science San Francisco, CA USA"
7,"Murić, Goran; Scheunert, Christian; Jorswieck,...",On modeling epidemics in networks using linear...,2015 IEEE 11th International Conference on Wir...,,,138-146,2015.0,IEEE
25,"RADA, POLOŽAJA ŽENA NA TRŽIŠTU;",ISTRAŽIVANJE O ULOZI ZNANJA IZ OBLASTI IKT I,,,,,2014.0,
9,"Murić, Goran; Bogojević, Dragan; Gospić, Nataša;",Interdependencies of communication and electri...,ICIST 2014 - 4th International Conference on I...,,,,2014.0,Society for Information Systems and Computer N...
46,"Muric, Goran; Macura, Dragana; Gospic, Natasa;...",An approach to assess criticality of elements ...,2013 11th International Conference on Telecomm...,,,,2013.0,
12,"Murić, Goran; Macura, Dragana; Gospić, Nataša;...",An Approach to Critical Information Infrastruc...,Business Information Security Conference BISEC...,,,,2013.0,
11,"Samcovic, Andreja; Muric, Goran;",Application of Digital Watermarking Technique ...,Business Information Security Conference BISEC...,,,,2013.0,
10,"Murić, Goran; Gospić, Nataša; Šelmić, Milica;",Protecting Critical Information Infrastructure...,International conference on Applied Internet a...,,,,2013.0,
5,"Murić, Goran; Gospić, Nataša; Bogojević, Dragan;",Proposal for possible approach for Critical In...,3rd International Conference on Information So...,,,,2013.0,
4,"Gospić, Nataša; Murić, Goran; Bogojević, Dragan;",The Method for Importance of Elements Assessme...,The Symposium on Novel Technologies in Postal ...,,,,2013.0,
3,"Murić, Goran; Macura, Dragana; Gospić, Nataša;...",An approach to assess criticality of elements ...,"Telecommunication in Modern Satellite, Cable a...",1.0,,141-144,2013.0,IEEE
1,"Gospić, Nataša; Murić, Goran; Bogojević, Dragan;",Managing critical infrastructure for sustainab...,E-society Journal,51.0,,,2012.0,
19,"Murić, Goran; Krsmanović, Maja;",ORSA - Organizing Software Application,AIIT - International Conference on Applied Int...,,,,2012.0,
6,"Bogojevic, Dragan; Gospic, Natasa; Muric, Goran;",Broadband universal service and access: trends...,2012 20th Telecommunications Forum (TELFOR),,,60-63,2012.0,IEEE
0,"Gospić, Nataša; Murić, Goran; Bogojević, Dragan;",Defining of Critical Telecommunication Infrast...,The Symposium on Novel Technologies in Postal ...,,,,2012.0,
2,"Krsmanović, Maja; Murić, Goran; Gospić, Nataša;",Improvement of children safety by using RFID b...,19thTelecommunications Forum (TELFOR) Proceedi...,,,130-133,2011.0,IEEE
27,"Ozer, Mert; Sapienza, Anna; Abeliuk, Andrés; M...",Discovering patterns of online popularity from...,,,,,,